### ISSUE TITLE
Proposal to better support "pdfmake-wrapper"

### ISSUE THREAD

**Issue by ZaLiTHkA** [Lugriz/pdfmake-font-generator#1]
first a little TL;DR story for the sake of context: I'm currently refactoring an Ionic 4 Angular 8 application, moving a bunch of business logic out of the "application" project into a separate "library" project in order to use it in multiple apps. in doing so, I ran into issues trying to get `ng-packagr` to do what I wanted with the custom font file I'm using (generated by this CLI tool).

after doing some research and considering different options, I decided the simplest solution was to convert my custom font file from JS to TS and refactor the file to export an object instead. so where *this* tool generates a file with the following:

```js
this.pdfMake = this.pdfMake || {};
this.pdfMake.vfs = {
  // "Font File.ttf": "base64-string"
};
```

I've changed it to the following:

```ts
export default {
  pdfMake: {
    vfs: {
      // "Font File.ttf": "base64-string"
    }
  }
};
```

the import statement to use this doesn't need to change and PDF generation works exactly as expected.

---

this got me wondering about what your (@Lugriz ) vision was for this tool: is it intended for use with the standard PdfMake library as the original author distributes it, or for use with your `pdfmake-wrapper` project? would you be open to contributions to this project?

to be honest, the first this I would *personally* like to do is rewrite this CLI tool using ~~`oclif`~~ something else, any objections to this idea? it *can* be done quite easily without losing backwards compatibility with the current usage.

**Comment by ZaLiTHkA** [comment]
small update to my message above: I'm not sure if `oclif` is really the best option.. from the project documentation it looks really awesome, but when you actually create a project and start working with it, the generated project structure and "expected commands" for running and build it are so opinionated, that any attempt to deviate from them to suite common workflows tends to break things.

also, I would like to have this installed as a dev-dependency without needing numerous `@oclif/...` libraries installed as well..

**Comment by Lugriz** [comment]
@ZaLiTHkA this tool is intended to work with both libraries (pdfmake and pdfmake-wrapper). I did not have problems with this tool. This library is open to contributions!. I'm not familiar with _oclif_ but I will take a look to it. I would like to have this library without extra dependencies, I consider to improve the problem you mentioned above. I will test it. If you want to contribute, it will be great. I would like to create a new complete CLI to pdfmake-wrapper which generates PDF structures, fonts and other things, but I don't know if it's a good idea for now.

**Comment by ZaLiTHkA** [comment]
> I would like to have this library without extra dependencies,

yup, that's why I ditched what I was working on with `oclif`.. what I had ended up with added extra dependencies to my application project when I installed it as a dev dependency.

> I would like to create a new complete CLI to pdfmake-wrapper which generates PDF structures, fonts and other things, but I don't know if it's a good idea for now.

I think that's a nice concept, but rather than making it "one tool", I would suggest one mono-repo with multiple projects contained under a package "namespace". for example:

* `@pdfmake-wrapper/core` could contain the library code as currently released under the name `pdfmake-wrapper`.
* `@pdfmake-wrapper/cli` could contain the CLI tool to generate the file required for the developer's project.

this has the benefit of still being module enough to allow the end user to install and manage them individually (like we currently can), but development on the project would happen in one folder with common dependencies, so it will be easy to keep them aligned when there are changes in one that affect the other.

---

either way, after ditching the `oclif` route just now, I did some quick and dirty hacks to the current CLI file on my side,just so that I can create the `.ts` file that *I'm* using (as described in my OP). I need to move on to other things now though (I am technically at work, so I have other corporate projects that I need to work on), so I'll carry on with this when I get home this evening. :)

**Comment by KingDarBoja** [comment]
@ZaLiTHkA Did you managed to provide the workaround to generate TS files for fonts rather that js ones? :D

**Comment by ZaLiTHkA** [comment]
@KingDarBoja sort of, but not all that elegantly... you can see the branch I used for this [over here](https://github.com/ZaLiTHkA/pdfmake-font-generator/tree/refactor/ts-output).

looking through this again now, I *would* actually like to come back and finish this one. 🤔  I'll ping you when I get a chance to do that. but in the meantime, hopefully my WIP changes will help a bit.

---

*edit*

with that said, I think the point of the issue I opened here (rewriting) is actually a bit of a moot point. this is intended to be a simple tool for taking input, converting it, and writing output..

so I'm actually going to close this off then, when I've cleaned things up a bit, I'll open a PR back to this project and ping you from there. 👍🏼
