### ISSUE TITLE
Cannot read property 'pdfMake' of undefined

### ISSUE THREAD

**Issue by contrerascoder** [Lugriz/pdfmake-font-generator#7]
I am managing to require the file generated by the command supplied by the package on my vue3 app to generate a pdf with custom font, but I can't import it because says me what you see in the title

It's possible in some way to import it on browser? How can I fix that error?

Thanks

**Comment by Lugriz** [comment]
@contrerascoder Thanks for using pdfmake-font-generator!

Sorry for the late replay. Can you provide more context or some code to see what could be the error?

**Comment by Lugriz** [comment]
Not details provided.
